import { LEVEL_LAYOUTS } from "./layouts/index";

export interface Tour {
  id: number;
  name: string;
  subtitle: string;
  tagline: string;
  brickSize: string; // e.g. "16x8"
  enemiesToSpawn: number;
  minEnemyHp: number;
  maxEnemyHp: number;
  clearRadius: number;
  concreteRatio: number;
  hasBoss: boolean;
  bossHp?: number;
  worldScale?: number; // Optional explicit size override
  difficulty: "Novice" | "Tactical" | "Heavy" | "Veteran" | "Elite" | "Extreme" | "Legendary";
  intel: string;
  squadDetails: string;
}

export const parseBrickSize = (size: string) => {
  const [w, h] = size.split("x").map(Number);
  // Scale down by 1.5x as requested by user
  return { w: Math.round((w || 32) / 1.5), h: Math.round((h || 16) / 1.5) };
};

export const getBrickDescription = (tour: Tour) => {
  const layout = LEVEL_LAYOUTS[tour.id];
  if (layout) {
    const rows = layout.trim().split("\n");
    if (rows.length > 0) {
      return `${rows[0].trim().length}x${rows.length} Grid`;
    }
  }
  const { w, h } = parseBrickSize(tour.brickSize);
  if (w === 32 && h === 16) return "Heavy Rect (32x16)";
  if (w === h) return `Heavy Square (${w}x${h})`;
  if (w > h) return `Heavy Beam (${w}x${h})`;
  return `Heavy Pillar (${w}x${h})`;
};

export const TOURS: Tour[] = [
  {
    id: 1,
    name: "Training Grounds",
    subtitle: "THE ETALON REFERENCE",
    tagline:
      "Standard classic red heavy bricks (32x16). Optimal performance design.",
    brickSize: "32x16",
    enemiesToSpawn: 10,
    minEnemyHp: 1,
    maxEnemyHp: 2,
    clearRadius: 100,
    concreteRatio: 0.15,
    hasBoss: true,
    bossHp: 8,
    worldScale: 1.2,
    difficulty: "Novice",
    intel:
      "Standard red clay bricks provide extensive destructibility. Excellent for cover-fire tactics and direct firefights.",
    squadDetails:
      "10 Light Patrol Tanks. Armored HP: 1-2. Level 1-2 scaling.",
  },
  {
    id: 2,
    name: "Symmetrical Grid",
    subtitle: "SQUARE DUST DISTRICT",
    tagline: "Dense formation of heavy bricks.",
    brickSize: "32x16",
    enemiesToSpawn: 12,
    minEnemyHp: 1,
    maxEnemyHp: 3,
    clearRadius: 120,
    concreteRatio: 0.2,
    hasBoss: true,
    bossHp: 8,
    worldScale: 1.2,
    difficulty: "Tactical",
    intel:
      "A classic maze layout using standard 16x8 brick units. Demands tactical positioning and flanking maneuvers.",
    squadDetails:
      "12 Mobile Recon Tanks. Armored HP: 1-3. Level 1-3 scaling.",
  },
  {
    id: 3,
    name: "Monolith Bastions",
    subtitle: "FORTRESS SECTOR",
    tagline: "Large defensive structures built from heavy modules.",
    brickSize: "32x16",
    enemiesToSpawn: 14,
    minEnemyHp: 2,
    maxEnemyHp: 4,
    clearRadius: 150,
    concreteRatio: 0.3,
    hasBoss: true,
    bossHp: 8,
    worldScale: 1.2,
    difficulty: "Heavy",
    intel:
      "Standard bricks arranged in massive formations. Takes significant firepower to carve paths through.",
    squadDetails:
      "14 Medium Infantry Tanks. Armored HP: 2-4. Level 2-4 scaling.",
  },
  {
    id: 4,
    name: "Fractured Ruins",
    subtitle: "MICRO-TESSELLATION SECTOR",
    tagline: "Open combat zone with heavy brittle defenses.",
    brickSize: "32x16",
    enemiesToSpawn: 16,
    minEnemyHp: 2,
    maxEnemyHp: 4,
    clearRadius: 100,
    concreteRatio: 0.1,
    hasBoss: true,
    bossHp: 8,
    worldScale: 1.2,
    difficulty: "Veteran",
    intel:
      "Bricks arranged in thin, fragile patterns. Combat lines disintegrate rapidly, turning corridors into open death zones.",
    squadDetails:
      "16 Swift Harasser Tanks. Armored HP: 2-4. Level 2-4 scaling.",
  },
  {
    id: 5,
    name: "Column Sanctum",
    subtitle: "PILLARED CORRIDOR",
    tagline: "Tall vertical heavy structures create severe shootaways.",
    brickSize: "32x16",
    enemiesToSpawn: 18,
    minEnemyHp: 3,
    maxEnemyHp: 5,
    clearRadius: 160,
    concreteRatio: 0.35,
    hasBoss: true,
    bossHp: 8,
    worldScale: 1.2,
    difficulty: "Elite",
    intel:
      "Narrow vertical pillars built from standard units. Horizontally shielded but offers dangerously open vertical corridors.",
    squadDetails:
      "18 Reinforced Sentinels + 1 Heavy Defender Boss (HP 8).",
  },
  {
    id: 6,
    name: "Chunky Assembly",
    subtitle: "ROBOTIC FABRICATOR BAYS",
    tagline: "Strategic horizontal cover arrays for advanced tactics.",
    brickSize: "32x16",
    enemiesToSpawn: 20,
    minEnemyHp: 3,
    maxEnemyHp: 5,
    clearRadius: 120,
    concreteRatio: 0.45,
    hasBoss: true,
    bossHp: 10,
    worldScale: 1.2,
    difficulty: "Veteran",
    intel:
      "Excellent horizontal cover arrays. The southern concrete defense zones are highly fortified, calling for flanking operations.",
    squadDetails:
      "20 Tactical Interceptor Tanks. Armored HP: 3-5. Level 3-5 scaling.",
  },
  {
    id: 7,
    name: "Stretched Girders",
    subtitle: "STEEL RAFT SCAFFOLDING",
    tagline: "Wide horizontal beam blocks restrict vertical vision.",
    brickSize: "32x16",
    enemiesToSpawn: 22,
    minEnemyHp: 4,
    maxEnemyHp: 6,
    clearRadius: 150,
    concreteRatio: 0.25,
    hasBoss: true,
    bossHp: 12,
    worldScale: 1.2,
    difficulty: "Heavy",
    intel:
      "Wide beam blocks restrict broad upward-downward vision while permitting quick lateral sweeps.",
    squadDetails:
      "22 Commando Stalkers. Armored HP: 4-6. Level 4-6 scaling.",
  },
  {
    id: 8,
    name: "Massive Bastions",
    subtitle: "CUBIC METROPOLIS OUTPOST",
    tagline: "Dense cluster of large industrial defensive units.",
    brickSize: "32x16",
    enemiesToSpawn: 24,
    minEnemyHp: 4,
    maxEnemyHp: 7,
    clearRadius: 180,
    concreteRatio: 0.55,
    hasBoss: true,
    bossHp: 14,
    worldScale: 1.2,
    difficulty: "Veteran",
    intel:
      "Extremely large industrial block towers. Excellent for weaving in and out of sight-lines.",
    squadDetails: "24 Heavy Siege Tanks. Armored HP: 4-7. Level 4-7 scaling.",
  },
  {
    id: 9,
    name: "Blockade Range",
    subtitle: "TACTICAL BARRICADES",
    tagline: "Standard bricks in a dense labyrinth formation.",
    brickSize: "32x16",
    enemiesToSpawn: 26,
    minEnemyHp: 5,
    maxEnemyHp: 8,
    clearRadius: 130,
    concreteRatio: 0.35,
    hasBoss: true,
    bossHp: 16,
    difficulty: "Elite",
    intel:
      "Highly optimized bricking layout. Creates dense maze corridors. Enemies here possess superior tracking.",
    squadDetails:
      "26 elite sniper and assault tanks. Armored HP: 5-8. Level 5-8 scaling.",
  },
  {
    id: 10,
    name: "Omega Core Complex",
    subtitle: "THE FINAL FRONTIER",
    tagline: "The high-density final node of global operations.",
    brickSize: "32x16",
    enemiesToSpawn: 28,
    minEnemyHp: 6,
    maxEnemyHp: 9,
    clearRadius: 200,
    concreteRatio: 0.6,
    hasBoss: true,
    bossHp: 15,
    worldScale: 1.2,
    difficulty: "Extreme",
    intel:
      "The ultimate showdown. High density heavy composite concrete walls guard center operations node.",
    squadDetails:
      "28 Elite Vanguards + 1 Ultimate Overlord Boss (HP 15).",
  },
  {
    id: 11,
    name: "Advanced Training",
    subtitle: "ETALON RETURN",
    tagline: "Classic patterns with upgraded enemy protocols.",
    brickSize: "32x16",
    enemiesToSpawn: 30,
    minEnemyHp: 2,
    maxEnemyHp: 3,
    clearRadius: 100,
    concreteRatio: 0.15,
    hasBoss: true,
    bossHp: 8,
    worldScale: 1.2,
    difficulty: "Veteran",
    intel: "Classic bricks. Excellent for cover-fire tactics.",
    squadDetails: "30 Light/Medium Tanks.",
  },
  {
    id: 12,
    name: "Urban Warfare",
    subtitle: "ETALON ASSAULT",
    tagline: "Grid-based warfare with high enemy density.",
    brickSize: "32x16",
    enemiesToSpawn: 32,
    minEnemyHp: 2,
    maxEnemyHp: 4,
    clearRadius: 100,
    concreteRatio: 0.15,
    hasBoss: true,
    bossHp: 8,
    worldScale: 1.2,
    difficulty: "Veteran",
    intel: "Standard shapes, but enemies are heavily armed.",
    squadDetails: "32 Medium Recon Tanks.",
  },
  {
    id: 13,
    name: "Red District",
    subtitle: "ETALON SIEGE",
    tagline: "Endless wave of red bricks and tough tanks.",
    brickSize: "32x16",
    enemiesToSpawn: 34,
    minEnemyHp: 3,
    maxEnemyHp: 5,
    clearRadius: 100,
    concreteRatio: 0.15,
    hasBoss: true,
    bossHp: 10,
    worldScale: 1.2,
    difficulty: "Heavy",
    intel: "More heavy infantry in classic red brick setups.",
    squadDetails: "34 Heavy Infantry Tanks.",
  },
  {
    id: 14,
    name: "Brick Hell",
    subtitle: "ETALON SHATTERED",
    tagline: "Intense firefights inside classic tight grids.",
    brickSize: "32x16",
    enemiesToSpawn: 36,
    minEnemyHp: 3,
    maxEnemyHp: 6,
    clearRadius: 120,
    concreteRatio: 0.2,
    hasBoss: true,
    bossHp: 12,
    worldScale: 1.2,
    difficulty: "Veteran",
    intel: "Thick enemy presence. Clear radius expanded.",
    squadDetails: "36 Swift Assault Tanks.",
  },
  {
    id: 15,
    name: "Clay Commander",
    subtitle: "ETALON BOSS",
    tagline: "Classic bricks. One big boss.",
    brickSize: "32x16",
    enemiesToSpawn: 38,
    minEnemyHp: 4,
    maxEnemyHp: 6,
    clearRadius: 140,
    concreteRatio: 0.2,
    hasBoss: true,
    bossHp: 16,
    worldScale: 1.2,
    difficulty: "Elite",
    intel: "A fearsome boss awaits in the standard red brick arena.",
    squadDetails: "38 Reinforced Sentinels + 1 Commander Boss.",
  },
  {
    id: 16,
    name: "Clay Storm",
    subtitle: "ETALON OVERDRIVE",
    tagline: "Overwhelming numbers, standard cover.",
    brickSize: "32x16",
    enemiesToSpawn: 40,
    minEnemyHp: 4,
    maxEnemyHp: 7,
    clearRadius: 100,
    concreteRatio: 0.25,
    hasBoss: true,
    bossHp: 14,
    worldScale: 1.2,
    difficulty: "Veteran",
    intel: "A huge fleet of enemies sweeping the red brick grids.",
    squadDetails: "40 Interceptor Tanks.",
  },
  {
    id: 17,
    name: "Red Concrete",
    subtitle: "ETALON FORTIFIED",
    tagline:
      "Standard bricks reinforced to concrete.",
    brickSize: "32x16",
    enemiesToSpawn: 42,
    minEnemyHp: 5,
    maxEnemyHp: 7,
    clearRadius: 120,
    concreteRatio: 0.4,
    hasBoss: true,
    bossHp: 14,
    worldScale: 1.2,
    difficulty: "Heavy",
    intel: "Classic brick shape but extreme concrete placement.",
    squadDetails: "42 Commando Tanks.",
  },
  {
    id: 18,
    name: "Brick Mayhem",
    subtitle: "ETALON ANARCHY",
    tagline: "Total chaotic warfare in the standard terrain.",
    brickSize: "32x16",
    enemiesToSpawn: 44,
    minEnemyHp: 5,
    maxEnemyHp: 8,
    clearRadius: 100,
    concreteRatio: 0.35,
    hasBoss: true,
    bossHp: 16,
    worldScale: 1.2,
    difficulty: "Elite",
    intel: "Massive waves of elite snipers.",
    squadDetails: "44 Elite Sniper Tanks.",
  },
  {
    id: 19,
    name: "Clay Apex",
    subtitle: "ETALON PINNACLE",
    tagline: "The absolute limit of standard brick encounters.",
    brickSize: "32x16",
    enemiesToSpawn: 45,
    minEnemyHp: 6,
    maxEnemyHp: 9,
    clearRadius: 120,
    concreteRatio: 0.45,
    hasBoss: true,
    bossHp: 18,
    worldScale: 1.2,
    difficulty: "Extreme",
    intel: "Near unbeatable odds.",
    squadDetails: "45 Ultimate Vanguards.",
  },
  {
    id: 20,
    name: "Etalon Overlord",
    subtitle: "ETALON OMEGA",
    tagline: "The absolute final battle in classical conditions.",
    brickSize: "32x16",
    enemiesToSpawn: 48,
    minEnemyHp: 7,
    maxEnemyHp: 10,
    clearRadius: 160,
    concreteRatio: 0.5,
    hasBoss: true,
    bossHp: 20,
    worldScale: 1.2,
    difficulty: "Extreme",
    intel: "Classical Red Bricks, highest level opposition.",
    squadDetails: "48 Maximum Level Sentries + 1 Omega Boss.",
  },
  {
    id: 21,
    name: "Iron Vanguard",
    subtitle: "HEAVY REINFORCED SECTOR",
    tagline: "Ultra-high density walls and supreme defensive armor.",
    brickSize: "32x16",
    enemiesToSpawn: 50,
    minEnemyHp: 8,
    maxEnemyHp: 11,
    clearRadius: 180,
    concreteRatio: 0.55,
    hasBoss: true,
    bossHp: 22,
    worldScale: 1.2,
    difficulty: "Elite",
    intel: "The terrain is reinforced with high-stress iron-clad barriers. Highly recommended to use demolition rounds.",
    squadDetails: "50 Heavy Iron-clad Vanguard Stalkers. Level 8-11 scaling.",
  },
  {
    id: 22,
    name: "Subterranean Maze",
    subtitle: "UNDERGOUND MATRIX CONTROLLERS",
    tagline: "A tight, complex layout featuring hyper-fast interceptors.",
    brickSize: "32x16",
    enemiesToSpawn: 52,
    minEnemyHp: 8,
    maxEnemyHp: 12,
    clearRadius: 140,
    concreteRatio: 0.6,
    hasBoss: true,
    bossHp: 24,
    worldScale: 1.2,
    difficulty: "Extreme",
    intel: "Every corridor here is a dynamic bottleneck where fast-shooting enemies lay ambushes.",
    squadDetails: "52 High-velocity Interceptor Drones. HP 8-12.",
  },
  {
    id: 23,
    name: "Industrial Core",
    subtitle: "PILLARED REACTOR BAYS",
    tagline: "Massive monoliths guarding energy processing pods.",
    brickSize: "32x16",
    enemiesToSpawn: 55,
    minEnemyHp: 9,
    maxEnemyHp: 13,
    clearRadius: 190,
    concreteRatio: 0.65,
    hasBoss: true,
    bossHp: 25,
    worldScale: 1.2,
    difficulty: "Extreme",
    intel: "Heavy steel structures line the reactor perimeter. A level-25 giant Core Overlord guards the master gate.",
    squadDetails: "55 Heavy Core Defenders + 1 Core Overlord Boss (HP 25).",
  },
  {
    id: 24,
    name: "Scorched Bastions",
    subtitle: "ASHEN FIRE REGISTRY",
    tagline: "Gigantic fortress networks designed to resist breaches.",
    brickSize: "32x16",
    enemiesToSpawn: 58,
    minEnemyHp: 9,
    maxEnemyHp: 14,
    clearRadius: 170,
    concreteRatio: 0.7,
    hasBoss: true,
    bossHp: 28,
    worldScale: 1.2,
    difficulty: "Legendary",
    intel: "The ultimate maze defense perimeter. Demands steady precision firing to slice through thick outer bastions.",
    squadDetails: "58 Elite Fortress Sentries and Commandos.",
  },
  {
    id: 25,
    name: "God Mode Arena",
    subtitle: "THE DEEPEST VOID",
    tagline: "The absolute zenith of campaign challenge protocols.",
    brickSize: "32x16",
    enemiesToSpawn: 65,
    minEnemyHp: 10,
    maxEnemyHp: 15,
    clearRadius: 220,
    concreteRatio: 0.75,
    hasBoss: true,
    bossHp: 35,
    worldScale: 1.2,
    difficulty: "Legendary",
    intel: "Every single enemy is a high-level apex predator. Only players with fully maxed-out systems can survive.",
    squadDetails: "65 Apex Sentinels + 1 Eternal Void Overlord Boss (HP 35).",
  },
];
