import { TourConfig } from "../TourConfig";

export const tour15: TourConfig = {
  id: 15,
  layout: `#CWWWC#CWWWC#.CWWWC.#CWWWC#CWWWC#CWWWC#
CWWWWW.WWWWW.CWWWC.WWWWW.WWWWW.WWWWWC
WWWWWW.WWWWW.WWWWW.WWWWW.WWWWW.WWWWWW
WWWWWW.WW#WW.WWWWW.WW#WW.WWWWW.WWWWWW
CW.WWW.WWWWW.CW.WC.WWWWW.WWW.WC.WWWWW
WWWWWW.WWWWW.WWWWW.WWWWW.WWWWW.WWWWWW
C....................................C
WWWWWW.WWWWW.WWWWW.WWWWW.WWWWW.WWWWWW
WWWWWW.WW#WW.WWWWW.WW#WW.WWWWW.WWWWWW
#WWWWW.WWWWW.#WWWW.WWWWW.WWWW#.WWWWW#
WWWWWW.WWWWW.WWWWW.WWWWW.WWWWW.WWWWWW
WWWWWW.WW#WW.WWWWW.WW#WW.WWWWW.WWWWWW
C....................................C
WWWWWW.WWWWW.WWWWW.WWWWW.WWWWW.WWWWWW
CWWWWW.WWWWW.CW.WC.WWWWW.WWWWW.WWWWWC
WWWWWW.WW#WW.W...W.WW#WW.WWWWW.WWWWWW
CWWWWW.WWWWW.CW.WC.WWWWW.WWWWW.WWWWWC
WWWWWW.WWWWW.WWWWW.WWWWW.WWWWW.WWWWWW
C....................................C
WWWWWW.WW#WW.WWWWW.WW#WW.WWWWW.WWWWWW
WWWWWW.WWWWW.WWWWW.WWWWW.WWWWW.WWWWWW
#WWWWW.WWWWW.#WWWW.WWWWW.WWWW#.WWWWW#
WWWWWW.WW#WW.WWWWW.WW#WW.WWWWW.WWWWWW
WWWWWW.WWWWW.WWWWW.WWWWW.WWWWW.WWWWWW
C....................................C
WWWWWW.WWWWW.WWWWW.WWWWW.WWWWW.WWWWWW
CW.WWW.WWWWW.CW.WC.WWWWW.WWW.WC.WWWWW
WWWWWW.WW#WW.WWWWW.WW#WW.WWWWW.WWWWWW
WWWWWW.WWWWW.WWWWW.WWWWW.WWWWW.WWWWWW
CWWWWW.WWWWW.CWWWC.WWWWW.WWWWW.WWWWWC
.....................................
#CWWWC#CWWWC#.CWWWC.#CWWWC#CWWWC#CWWWC`
};
