import { TourConfig } from "../TourConfig";

export const tour11: TourConfig = {
  id: 11,
  layout: `WWWWWW.WWWWW.WWWWW.WWWWW.WWWWW.WWWWWW
WWWWWW.WWWWW.WWWWW.WWWWW.WWWWW.WWWWWW
W.W.WW.WWWWW.WWWWW.WWWWW.WWWWW.WW.W.W
WWW.WW.WWWWW.WWWWW.WWWWW.WWWWW.WW.WWW
WWWWWW.WWWWW.W.W.W.WWWWW.WWWWW.WWWWWW
WWWWWW.WWWWW.WWWWW.WWWWW.WWWWW.WWWWWW
W....................................W
WWWWWW.WWWWW.WWWWW.WWWWW.WWWWW.WWWWWW
WWWWWW.WWWWW.WWWWW.WWWWW.WWWWW.WWWWWW
WW.W.W.WW.WW.WWWWW.WW.WW.W.W.W.W.WWWW
WW.WWW.WWWWW.WW.WW.WWWWW.WWW.W.WWWWWW
WW.WWW.WWWWW.WWWWW.WWWWW.WWW.W.WWWWWW
W....................................W
WWWWWW.WWWWW.WWWWW.WWWWW.WWWWW.WWWWWW
WWWWWW.WWWWW.WW.WW.WWWWW.WWWWW.WWWWWW
WWWWWW.WWWWW.W...W.WWWWW.WWWWW.WWWWWW
WWWWWW.WWWWW.WW.WW.WWWWW.WWWWW.WWWWWW
WWWWWW.WWWWW.WWWWW.WWWWW.WWWWW.WWWWWW
W....................................W
WWWWWW.WWWWW.WWWWW.WWWWW.WWWWW.WWWWWW
WW.WWW.WWWWW.WWWWW.WWWWW.WWW.W.WWWWWW
WW.W.W.WW.WW.WWWWW.WW.WW.W.W.W.W.WWWW
WWWWWW.WWWWW.WWWWW.WWWWW.WWWWW.WWWWWW
WWWWWW.WWWWW.WWWWW.WWWWW.WWWWW.WWWWWW
W....................................W
WWWWWW.WWWWW.WWWWW.W.W.W.WWWWW.WWWWWW
WWW.WW.WWWWW.WWWWW.WWWWW.WWWWW.WW.WWW
W.W.WW.WWWWW.WWWWW.WWWWW.WWWWW.WW.W.W
WWWWWW.WWWWW.WWWWW.WWWWW.WWWWW.WWWWWW
WWWWWW.WWWWW.WWWWW.WWWWW.WWWWW.WWWWWW
.....................................`
};
