import { TourConfig } from "../TourConfig";

export const tour17: TourConfig = {
  id: 17,
  layout: `CCCCCC.CCCCC.CWWWC.CCCCC.CCCCCC
CWWWWC.CWWWC.CWWWC.CWWWC.CWWWWC
CWWWWC.CWWWC.CWWWC.CWWWC.CWWWWC
CCCCCC.CCCCC.CC.CC.CCCCC.CCCCCC
CWWWWC.CWWWC.CWWWC.CWWWC.CWWWWC
CWWWWC.CWWWC.CWWWC.CWWWC.CWWWWC
C..............................C
CCCCCC.CCCCC.CWWWC.CCCCC.CCCCCC
CWWWWC.CWWWC.CWWWC.CWWWC.CWWWWC
CWWWWC.CC.CC.CWWWC.CC.CC.CWWWWC
CWWWWC.CWWWC.CWWWC.CWWWC.CWWWWC
CCCCCC.CCCCC.CWWWC.CCCCC.CCCCCC
C..............................C
CCCCCC.CCCCC.CCCCC.CCCCC.CCCCCC
CWWWWC.CWWWC.CW.WC.CWWWC.CWWWWC
CWWWWC.CWWWC.C...C.CWWWC.CWWWWC
CWWWWC.CWWWC.CW.WC.CWWWC.CWWWWC
CCCCCC.CCCCC.CCCCC.CCCCC.CCCCCC
C..............................C
CCCCCC.CCCCC.CWWWC.CCCCC.CCCCCC
CWWWWC.CWWWC.CWWWC.CWWWC.CWWWWC
CWWWWC.CC.CC.CWWWC.CC.CC.CWWWWC
CWWWWC.CWWWC.CWWWC.CWWWC.CWWWWC
CCCCCC.CCCCC.CWWWC.CCCCC.CCCCCC
C..............................C
CWWWWC.CWWWC.CWWWC.CWWWC.CWWWWC
CWWWWC.CWWWC.CWWWC.CWWWC.CWWWWC
CCCCCC.CCCCC.CC.CC.CCCCC.CCCCCC
CWWWWC.CWWWC.CWWWC.CWWWC.CWWWWC
CWWWWC.CWWWC.CWWWC.CWWWC.CWWWWC
...............................
CCCCCC.CCCCC.CWWWC.CCCCC.CCCCCC`
};
