import { TourConfig } from "../TourConfig";

export const tour8: TourConfig = {
  id: 8,
  layout: `W..CWWW.CWW..WCWWCC.CWWWC.WWWW..WWW.WW
WW.WWW.WWWWW.WWWWC.WCWWW.WCWWW..WCW..W
WW.WWW.WWCCW.WC.WW.WWWWW.WWWCW.WWCWW.W
WWWWWW.W..CW.W.CWW.C.CWW.W..CW.WCWWW..
WWWW.W.WWWCW.WCCCW.WWWWW.WWCCW.WCWWW.W
WWWCWW.WWCCC..CWWW.WWWCW.WWWWW.WWCCW.W
C....................................W
WWW.WC.CW.CC.WWWWW.WWWWW.CCW.C.CWWWC.C
.WWWWW.CCWWW.WWWWW.CWWWW.CWCW..WWC.W.W
W.CWCW.WCWWW.WWCWW.WWWWC.WW.WW.CW.CW.W
WCWWCW.WWCWW.WCWWW.WWWWW.WCWWW.CW.W..W
WWCWWC.W..WW.CW.W..CWWWW.CWCWC.CWWWW.W
.....................................C
WWWWWC.WWWWC.WWWCW.CWWWW.WWWWW.C.WWW..
WWWW.W.WWWWW.WWWWW...WWW.WWWWW.WWWWW..
.WWCWW.WWW.W.WWWCC.WWCWW.WWWWW.CWWCW..
WWWWW..WWWCW.CWW.W.WCWCW.WW.CW.WCWW..W
W.WWWW.WCWWW.WWCW.....W...CWCW.CC.WW.W
.....................................C
WWW.WW.W.WWW.WWWW.....CW.CWWWW.WW.WW.W
CWCCWC..WWWW.WWW......WW.WW.WW.WW.CW.W
CCWCWW.CWWWC.W.CW.....CW.CWWWW..WWWW.W
.CWW.W.WWCCW.CCWWW.WWCWW.WWWWC.WWWWW.W
WW.WWW.WWWWW.WWWWW...CWW.WWWWW.CWWWW..
W....................................C
W.WWWC.WCWWW.WCWWW.WCWWW.WWWW..WCWCW.W
WWWCWW.WW.C..W.WWC.WCCCW.WCWWW.WWWWW..
WWWWWC.CWCWW..W.WC.CWWWW.WWWWW.W.WWW.W
WWWCWW.WCWCW.WWWW..WWWWC.WCWWW.WWWWW.W
WW.W.W.WWWW..WWWCW.CCW.W.CW.WW.CWW.W.W
W....................................W
.WW.CC..WWWW.C.WWW.WW.WW.C.WWW.WWWWC.W
WWW.WW.CWWW...WC.W.WWWWW.W.WCW.CWWW..W
WWWWW..CWWWW.WWWCW.WWWCC..WWWC.WWCWC.W
.WCCCW.WWWWW...WWW.WWWWC.WWWWW.CWWCW.W
WW.WWC.CWWCW.WWWCC.WCWWW.WWWWW.WWWWW.W
C....................................W
WC.WWWW.CWCWWWCC.CW.W.WWW.WW.CWWW.WWWW`
};
