import { TourConfig } from "../TourConfig";

export const tour7: TourConfig = {
  id: 7,
  layout: `WCCWW.WCCWWWW.WWCCWWCWCWWWCWCWWWWC...
CWWCWC.WWWWW.WWWWC.WWCWW.WWW.W.WWCWCW
W.WWWW.WWWWW.WWWWW.WWWWW.WW.WW.WWWCWW
.WWWWW.WCWWW.WWWWW.WWCWW.WWWW..WCC..W
WWWWWW..W.CW.W.CWW..WWW..CCW.W.CWWWWC
WWWWWW.CCWWC.WWWW..WCWWW.CWWWW.WWWWCC
W...................................W
CWWCWW.WWCW..WWCCC.WWWWC.WWCWW...CCWC
WCWWWW.WW.WC.W.CWW.WWWWW.WW.C..WWWCWW
W.WWWW.WWWWW.WCWWW.WWWWW.WWWC..WCWCWW
WWCCWC.WCWWW.CWW.W..WWWW.WWWWW.WWWCWC
WWWCWC.WWWWW.WCWWC.WWW.W.CWCWW.WWWCWW
....................................W
WWWWWW.CWWCW.WWWWW.CWWWW.WWWCW..WWW.W
.WWWC..WWWWC.WWWCW.WWWCW.WWCWW.W.CWCW
WWWWWW.WWWWW.WWWWW.W.WWW.WW.WW..WWWWW
WWWWWW.WWW.C.WWW.....CCW.CWWWW.CWWC.W
WWWWWW.WWC.C.CWW.....WWW.W.WWW.CWWWCW
W...................................W
WWCW.W.WWWW..CWW.....CWW.WCWCW.CWWWWW
WWWWWW.WCWWW.WCW......CW.WW.WW.WWWW.W
WWWWWW.WWWWW.WCWWW.WWWCW.WW.WW.WW..W.
CWWCWW..WWWW.WW.WW..WWWW.CW.WW.WCWCWW
.WWW.W.WWCWW.WWWWW.CW.W..CWWWW.WWWWCW
C...................................C
W.WCCW.WWWWW.WWWWW.CWWWW...CWW.WCWW.W
CWWWWW.WW.WW.WWWCW.CWWCC.CWWWW.WWWWWW
WW.CWW.WC.WC.WWCWW.C..WW.WWWWW.WWWWCW
WWCWWW.WWCCW.WCCCW.CWWWW.WWCWW.CCCWW.
WW.CW..WWWWC.WWWWC.WWCWW.WWCCW.WCWWWW
W...................................W
WWWWWW.W.WWW.W.WC..WWWWW.WCWW..CWWWWW
WWWW.C..WWCW.WWWWW.WWWCW..WWWW.WWWWWW
.WWCWW.WWWWC.WCWW...WCWW.WWWWW.WCWWWW
WWWWW..CWWWW.WWWCW.WCCCW.WWCWW.WWWWCW
WWWWWW.WWWCW.W.WW..WWWWW.WWCWC.C.WWWW
WWCCWWCWWWW.WWWCWWWCWWWWW.WWWWWWW.WWW`
};
