import { TourConfig } from "../TourConfig";

export const tour18: TourConfig = {
  id: 18,
  layout: `CWWCWW.CWWCW.CWWCW.CWWCW.CWWCW.WWCWC
WWWWWW.WWWWW.WWWWW.WWWWW.WWWWW.WWWWWW
CW.WWW.WWWWW.CWWWC.WWWWW.WWW.WC.WWWWW
WWWWWW.WWWWW.WWWWW.WWWWW.WWWWW.WWWWWW
WWWWWW.WW.WW.WWWWW.WW.WW.WWWWW.WWWWWW
CWWCWW.CWWCW.CW.WC.CWWCW.CWWCW.WWCWWC
W....................................W
WWWWWW.WWWWW.WWWWW.WWWWW.WWWWW.WWWWWW
CWWCWW.WW.WW.CWWCW.WW.WW.WWCWW.CWWCWW
WWWWWW.WWWWW.WWWWW.WWWWW.WWWWW.WWWWWW
CWWCWW.CWWCW.CWWCW.CWWCW.CWWCW.CWWCWW
WWWWWW.WWWWW.WWWWW.WWWWW.WWWWW.WWWWWW
W....................................W
CWWCWW.WWWWW.CWWCW.WWWWW.WWWWW.CWWCWW
WWWWWW.CWWCW.WWWWW.CWWCW.WWWWW.WWWWWW
WWWWWW.WWWWW.W...W.WWWWW.WWWWW.WWWWWW
WWWWWW.CWWCW.WWWWW.CWWCW.WWWWW.WWWWWW
CWWCWW.WWWWW.CWWCW.WWWWW.WWWWW.CWWCWW
W....................................W
WWWWWW.WWWWW.WWWWW.WWWWW.WWWWW.WWWWWW
CWWCWW.CWWCW.CWWCW.CWWCW.CWWCW.CWWCWW
WWWWWW.WWWWW.WWWWW.WWWWW.WWWWW.WWWWWW
CWWCWW.WW.WW.CWWCW.WW.WW.WWCWW.CWWCWW
WWWWWW.WWWWW.WWWWW.WWWWW.WWWWW.WWWWWW
W....................................W
CWWCWW.CWWCW.CW.WC.CWWCW.CWWCW.WWCWWC
WWWWWW.WW.WW.WWWWW.WW.WW.WWWWW.WWWWWW
WWWWWW.WWWWW.WWWWW.WWWWW.WWWWW.WWWWWW
CW.WWW.WWWWW.CWWWC.WWWWW.WWW.WC.WWWWW
WWWWWW.WWWWW.WWWWW.WWWWW.WWWWW.WWWWWW
.....................................
CWWCWW.CWWCW.CWWCW.CWWCW.CWWCW.WWCWWC`
};
