import { TourConfig } from "../TourConfig";

export const tour16: TourConfig = {
  id: 16,
  layout: `WWWWWWWWWWWWW.WWWWW.WWWWWWWWWWWWW
WWWWWW.WWWWW.WWWWW.WWWWW.WWWWWW
WW...W.WWWWW.WWWWW.WWWWW.W...WW
WWWWWW.WW.WW.WWWWW.WW.WW.WWWWWW
WWWWWW.WWWWW.WW.WW.WWWWW.WWWWWW
W................................W
WWWWWW.WWWWW.WWWWW.WWWWW.WWWWWW
WW...W.WW.WW.WWWWW.WW.WW.W...WW
WWWWWW.WWWWW.WWWWW.WWWWW.WWWWWW
WWWWWW.WWWWW.WWWWW.WWWWW.WWWWWW
W................................W
WWWWWW.WWWWW.WW.WW.WWWWW.WWWWWW
WWWWWW.WWWWW.W...W.WWWWW.WWWWWW
WWWWWW.WWWWW.WW.WW.WWWWW.WWWWWW
W................................W
WWWWWW.WWWWW.WWWWW.WWWWW.WWWWWW
WWWWWW.WWWWW.WWWWW.WWWWW.WWWWWW
WW...W.WW.WW.WWWWW.WW.WW.W...WW
WWWWWW.WWWWW.WWWWW.WWWWW.WWWWWW
W................................W
WWWWWW.WWWWW.WW.WW.WWWWW.WWWWWW
WWWWWW.WW.WW.WWWWW.WW.WW.WWWWWW
WW...W.WWWWW.WWWWW.WWWWW.W...WW
WWWWWW.WWWWW.WWWWW.WWWWW.WWWWWW
WWWWWWWWWWWWW.WWWWW.WWWWWWWWWWWWW`
};
