import { TourConfig } from "../TourConfig";

export const tour1: TourConfig = {
  id: 1,
  layout: `WWWWWWWWW.WWWWWWWWWWWWWWWWWWW.WW
WWW.W..WWWWW.W.WWW.WWWWW.WWWWWW.
WWWW.W.WWWWW.WWWWW.WW.WW.W.WWWW.
WWWWWW.WWWWW.W.WW..WWWWW.WWWWWW.
WW.W...WWWWW.WWWWW.WWWWW..WWW.W.
.WWWWW.WWWWW.WWWWW.WWWWW.WWW.WW.
W..............................W
WWWWW..WWWWW.WW.WW.W.WWW.WWWWW.W
WWWW.W.WW..W...WWW.WWWW..WWWWW.W
WWWWWW.WWW.W.WWW.W.WWWWW..W.WW.W
WWWWWW.WW..W.WWWWW..WWWW.WWWWW.W
WWWWWW.WWWWW.WWWWW.WWWW..WW.WW.W
W..............................W
WWWWWW.WWWWW.WWWWW.WWWWW.WWWWW.W
WWWWWW.WWWWW.W.....WWWWW.WWWWW.W
W..WWW.W.WWW.......WWWWW.WWWWW.W
WWWW.W.WWWWW.W.....W..WW.WWWW..W
WWWWW..WWWWW.W.....WWWWW.WWWWW.W
W..............................W
WW.WWW.WWWWW.WWWWW.WWWWW.WW.WW.W
WWWWWW.WWW.W.WW.WW.WWWW..WWWWW.W
WWW.WW..WWWW.WWWWW.WWWWW.WWWWW.W
WWWW.W.WW.WW.WWWW..WWWWW.WWWWW.W
WWWWW..WWWWW.WWWWW.WWWWW.WWWWW.W
W..............................W
WWWWWW.WW.WW.WWWWW.WWWWW.WWWWW.W
W..WWW.WWWWW.WWWWW.WWWWW.WWWWW.W
WWWWWW.WWWWW.WWW.W.WWW.W.WWWWW.W
WWW.WW.WWW...WWWWW.WWWWW.WWWWW.W
WWWWWW.WWWWW.WWWWW.WWWWW..WWWW.W
W..............................W
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW`
};
