import { TourConfig } from "../TourConfig";

export const tour6: TourConfig = {
  id: 6,
  layout: `WWWWWWWCWWW.CWWWWWW.WWCWWWWWCWW.WCWW
W.WW.W.WCWWC.CCWWW.WW.WW.WWWWC.WW.WW
WCWWCW.CWCWW.C.WCW.WCWWW.WWWWC.W.WWW
WCW.WW.W.WWW.W..CW.WWCCW.WWWWW..WWWW
CWWWWW.WWCCC.WWWWW.CCWWW.WWWW...WW.W
WWWW.W.CWWWW.WW.WW.WWWWW.WCCWC.WWWWW
W...................................
WWWWWW..WCWW.W.WWC.CWWWW.WWWWW.WWWWC
WWC.CW.WW.WW.W.WWW.WW.WW.WWWWW.WWWCW
WWWCCW.WWWW...WCCW.W.WWW.WWCWC.WCWWW
CWWWWW.WWWWW.CWW.W.CWWWW.W.CWW.C.WWW
CCWCWW..W.WW.WWWWW.WWWWW.W.WW..CWWC.
W..................................W
WCWW.C..WWCW.WWWWW.WCWWC.CCCWW.WW.CC
.WCCWW.WCCWC.WWWWW.WWCWW.W.WCC..WWCW
CWWWWW.WWC...WCWWC.CWCWC.WWWWW.WCW..
WCWWWW.WWWC..WWW.....WWW.WWWCW.WWCWW
.WWCWW.WWWWW.WW......WWW.WW.WW.CCC.C
W..................................W
WWWCWW.WC.WW.WWW.....WWW.CWWCW.CWW.W
CCCWW...WCCC.WW......CW..CWC.W.WCWWW
WWWWWW.WWW.C.WWWWW.WCWWW.WW.WW.WWWWW
.WCC.W.W.WCW.WWWWW.WWWWW.WWWWW.WWWWW
WW.CWW..CWWW..CWC..WWCWW.WWWWW.WWWWW
...................................W
.WWWCW.WWCWW.WCW.W..WWWW.CWWWC.WWCWW
WWWWCW.C.WWW.CWWCC.WCWC..CWWCW.CW.WW
CWCWCW.WWWWC..W.CC.WWWWC.CWCWW.CCCC.
WWWWWW.WWCWW.WC..W.WCWWW..WWW..WWWWC
WWWWCC.WCCWW.CWWCW.WWWWW.CW.WW.WWCWW
W..................................W
WWWWWW.WWWCW.WWWWW.W.WCW.WCWCW.CWWCW
.WCCCW.WW.WW.CWC.C.W.W.W.WW.CC.CCWWW
.CWWWW..CWWW.WWW.W.WWWW..CCCWW.WWCWW
CWWWWW.WWWWW...WC..WWWWW.WCW.W.WWCWC
WWWWWWC.WCWCWWWWWWWWWWWWC.WWWWCWCWWC`
};
