import { TourConfig } from "../TourConfig";

export const tour19: TourConfig = {
  id: 19,
  layout: `#CWWC#.CWWWC.#CWWC#.CWWWC.#CWWC#.CWWWC#
CWWWWW.WWWWW.CWWWC.WWWWW.WWWWWC.WWWWWC
WWWWWW.WW#WW.WWWWW.WW#WW.WWWWWW.WWWWWW
CWWWWW.WWWWW.CWWWC.WWWWW.WWWWWC.WWWWWW
#CWWC#.CWWWC.#C.C#.CWWWC.#CWWC#.CWWWC#
CWWWWW.WWWWW.CWWWC.WWWWW.WWWWWC.WWWWWW
C....................................C
#CWWC#.CWWWC.#CWWC#.CWWWC.#CWWC#.CWWWC
CWWWWW.WW#WW.CWWWC.WW#WW.WWWWWC.WWWWWW
WWWWWW.WWWWW.WWWWW.WWWWW.WWWWWW.WWWWWW
CWWWWW.WWWWW.CWWWC.WWWWW.WWWWWC.WWWWWW
#CWWC#.CW#WC.#CWWC#.CW#WC.#CWWC#.CWWWC
C....................................C
CWWWWW.WWWWW.CWWWC.WWWWW.WWWWWC.WWWWWW
#CWWC#.CWWWC.#C.C#.CWWWC.#CWWC#.CWWWC#
CWWWWW.WW#WW.C...C.WW#WW.WWWWWC.WWWWWW
#CWWC#.CWWWC.#C.C#.CWWWC.#CWWC#.CWWWC#
CWWWWW.WWWWW.CWWWC.WWWWW.WWWWWC.WWWWWW
C....................................C
#CWWC#.CW#WC.#CWWC#.CW#WC.#CWWC#.CWWWC
CWWWWW.WWWWW.CWWWC.WWWWW.WWWWWC.WWWWWW
WWWWWW.WWWWW.WWWWW.WWWWW.WWWWWW.WWWWWW
CWWWWW.WW#WW.CWWWC.WW#WW.WWWWWC.WWWWWW
#CWWC#.CWWWC.#CWWC#.CWWWC.#CWWC#.CWWWC
C....................................C
CWWWWW.WWWWW.CWWWC.WWWWW.WWWWWC.WWWWWW
#CWWC#.CWWWC.#C.C#.CWWWC.#CWWC#.CWWWC#
CWWWWW.WWWWW.CWWWC.WWWWW.WWWWWC.WWWWWW
WWWWWW.WW#WW.WWWWW.WW#WW.WWWWWW.WWWWWW
CWWWWW.WWWWW.CWWWC.WWWWW.WWWWWC.WWWWWC
.....................................
#CWWC#.CWWWC.#CWWC#.CWWWC.#CWWC#CWWWC#`
};
