import { TourConfig } from "../TourConfig";

export const tour13: TourConfig = {
  id: 13,
  layout: `WWWWWWWWWWWWWWWWWWW.WWWWWWWWWWWWWWWWWWW
WWWWWW.WWWWW.WWWWW.WWWWW.WWWWW.WWWWWW
W.WWWW.WWWWW.WWWWW.WWWWW.WWWWW.WWWW.W
W.WWWW.WW.WW.WWWWW.WW.WW.WWWWW.WWWW.W
W.WWWW.WWWWW.WW.WW.WWWWW.WWWWW.WWWW.W
W.WWWW.WWWWW.WWWWW.WWWWW.WWWWW.WWWW.W
W....................................W
W.WWWW.WWWWW.WWWWW.WWWWW.WWWWW.WWWW.W
W.WWWW.WWWWW.WW.WW.WWWWW.WWWWW.WWWW.W
W.WWWW.WW.WW.WWWWW.WW.WW.WWWWW.WWWW.W
W.WWWW.WWWWW.WWWWW.WWWWW.WWWWW.WWWW.W
WWWWWW.WWWWW.WWWWW.WWWWW.WWWWW.WWWWWW
W....................................W
WWWWWW.WWWWW.WWWWW.WWWWW.WWWWW.WWWWWW
W.WWWW.WWWWW.WWWWW.WWWWW.WWWWW.WWWW.W
W.WWWW.WWWWW.W...W.WWWWW.WWWWW.WWWW.W
W.WWWW.WWWWW.WWWWW.WWWWW.WWWWW.WWWW.W
WWWWWW.WWWWW.WWWWW.WWWWW.WWWWW.WWWWWW
W....................................W
WWWWWW.WWWWW.WWWWW.WWWWW.WWWWW.WWWWWW
W.WWWW.WWWWW.WWWWW.WWWWW.WWWWW.WWWW.W
W.WWWW.WW.WW.WWWWW.WW.WW.WWWWW.WWWW.W
W.WWWW.WWWWW.WW.WW.WWWWW.WWWWW.WWWW.W
W.WWWW.WWWWW.WWWWW.WWWWW.WWWWW.WWWW.W
W....................................W
W.WWWW.WWWWW.WWWWW.WWWWW.WWWWW.WWWW.W
W.WWWW.WWWWW.WW.WW.WWWWW.WWWWW.WWWW.W
W.WWWW.WW.WW.WWWWW.WW.WW.WWWWW.WWWW.W
W.WWWW.WWWWW.WWWWW.WWWWW.WWWWW.WWWW.W
WWWWWW.WWWWW.WWWWW.WWWWW.WWWWW.WWWWWW
W....................................W
WWWWWWWWWWWWWWWWWWW.WWWWWWWWWWWWWWWWWWW`
};
