import { TourConfig } from "../TourConfig";

export const tour10: TourConfig = {
  id: 10,
  layout: `WWWWWWWWWWCWCWCWW.WWWWWWW.CCWWCWWWWCWWWW
WWWWWW.WWCWC.WWWWW.WWCWW.WWW.C.WCWCW.CWC
WWWWW#.WWC.W.WCWCW.WW#WW.WWW.W.CW#WW.WWW
WCWWCC.WWCWW.WCWWW.WCWWW.WWCWC.WWWWW.W.W
WWCWWW..CWWC.W.WW#..WWCW.WWWWW.WW.WW.W#W
WWWWWW.WWWC..#.#WW.WWWW#.#.WC..CCWCW.C.W
W......................................W
WWWWCW.WCWWC.CWWWW..WCWW.WWWWW..CWWW.WWW
C.WW.W.WWC.W.WW#WW.WW.WC.W.CWC.WCCWW.WCW
CWWWWW..WWWW..WWCW.WWWWW.WWW.W.W.WWW.WWC
W#WCWW.WWWWW.WCWW..WWWWW.WWWWW.WWWW#.W..
WCWWW#.W.WWC..WWWW.WWWWW.WWW.W.W#WWW.CWW
W......................................W
WWWW.W.WW.WW.WWWWW.WWWWW.WCWWW.CWCCC.#WW
WW.WCW.WCWW...WWWW.WW#WW.WWWWW..WCWW..WW
WW.WWW.WWWCW.WWWCW.WWCWW.WWWWW.WWWWW.WWW
WWW.CW.WWCWW.#WW...WWCWC.WWWWW.W.WWW.W.W
W#CWWW.C.WWW.WWWWC.W.CCW.#CWWW.WWWWW.WWW
W......................................W
WWWCWC.WCW.W.WWCWW.....W..WCWW.WWCWW.WWW
WCW.WW.CWWCW.WC#WC.....W.WCWWW.WW.WW...W
.CWCW..CCWWW.WWW.W.....W.WWWWW.WWWCC.CWW
WWWCW#.WWWWW.WW#WW.......WW#WW.WWW.C.WWW
CWWWW..CWCWC.WWW.W.WWCWW..CWCC.WWCWW.CWW
W......................................C
WC#C.W.WWW#W.WW.WW.WCWCW.CCCWW.W..CW.WWW
WWWWCW..C.WW.WWWCW.WWWWW.WW.CC.WW#WW.WWW
CWWWWW.W#WWW.WWWWC.CW.WC.WCCWW.W.WWW.WCW
CWWWC..WWWWW.WWWWW..WW#C.WWWCW.WWCWC.#WW
W.WWWW.WCCW..CCWW..W..CW.WW.WW.WCWCC..WW
W......................................W
WWWWWW.WWWWW.W.WWC.WWWWW.WWWWW.W.WCW.#WW
WWCWWW.WCW.W.CWWWW.#CCW...WWW..WCWW..WWW
CWWWWW.CWWWW.WW#CW.W.CCW.W#WWW.WCW.W.WW.
WWC.WW.CCW.W.WCCCW..W.C#.WW....WWWCW.WWW
CWCCWC.WWWWC.WWCCW.WWCWW.WWWWW.CWWCW.CWW
W.......................................
.WWWW..WWWWW.C.WWW.CWWWC.WWWWC.W#.WW.WWW
CWW#WC.WCWW#.WCWWW.CWW#W.CWCWW.WW.WC.WWW
WCW#WWWCW.CWWWWWWW#CWWWC#WWWWWWWCWWWW#WW`
};
