import { TourConfig } from "../TourConfig";

export const tour20: TourConfig = {
  id: 20,
  layout: `##CWC##CWC##CWC##.CWC.##CWC##CWC##CWC##
#CWWWC#CWWC#CWWWC.CWWWC.CWWWC#CWWC#CWWC#
CWWWWWWWWWWW.CWWWC.CWWWC.WWWWWWWWWWWCWWWC
WWWWWW.WWWWW.WW#WW.WW#WW.WWWWW.WWWWWWWWW
#CW.WC.CW#WC.CWWWC.CWWWC.CW#WC.CW.WC#WWC
CWWWWW.WWWWW.CWWWC.CWWWC.WWWWW.WWWWWCWWW
C......................................C
#CWWWC#CWWWC.#CWC#..#CWC#.CWWWC#CWWWC#WC
CWWWWW.WW#WW.CWWWC.CWWWC.WW#WW.WWWWWCWWW
WWWWWW.WWWWW.WWWWW.WWWWW.WWWWW.WWWWWWWWW
CWWWWW.WWWWW.#CWWC.CWWC#.WWWWW.WWWWWCWWW
#CW#WC.CW#WC.CWWWC.CWWWC.CW#WC.CW#WC#WWC
C......................................C
CWWWWW.WWWWW.CWWWC.CWWWC.WWWWW.WWWWWCWWW
#CWWWC.CWWWC.#CWC#.#CWC#.CWWWC.CWWWC#WWC
CWWWWW.WW#WW.CW.WC.CW.WC.WW#WW.WWWWWCWWW
#CWWWC.CWWWC.#CWC#.#CWC#.CWWWC.CWWWC#WWC
CWWWWW.WWWWW.CWWWC.CWWWC.WWWWW.WWWWWCWWW
C......................................C
#CW#WC.CW#WC.CWWWC.CWWWC.CW#WC.CW#WC#WWC
CWWWWW.WWWWW.#CWWC.CWWC#.WWWWW.WWWWWCWWW
WWWWWW.WWWWW.WWWWW.WWWWW.WWWWW.WWWWWWWWW
CWWWWW.WW#WW.CWWWC.CWWWC.WW#WW.WWWWWCWWW
#CWWWC#CWWWC.#CWC#..#CWC#.CWWWC#CWWWC#WC
C......................................C
CWWWWW.WWWWW.CWWWC.CWWWC.WWWWW.WWWWWCWWW
#CW.WC.CW#WC.CWWWC.CWWWC.CW#WC.CW.WC#WWC
WWWWWW.WWWWW.WW#WW.WW#WW.WWWWW.WWWWWWWWW
CWWWWWWWWWWW.CWWWC.CWWWC.WWWWWWWWWWWCWWWC
#CWWWC#CWWC#CWWWC..CWWWC.CWWWC#CWWC#CWWC#
.......................................
##CWC##CWC##CWC##.CWC.##CWC##CWC##CWC##`
};
