import { TourConfig } from "../TourConfig";

export const tour5: TourConfig = {
  id: 5,
  layout: `WWC.W.CWWCWWWWWWWWWW.WWWWWWWWWWCWW.
W.CWWW.WW.CW.WWWW..WWWWW.WWCCW.WWWW
WWWWWW..WCWW.WWWCW.W.WWC.W.WWW..CCC
WW.WWW.WCWWW.WWWWW.WCWCW.WWWWW.CWWW
WWWWCW.CCWCW..CW.W.WCWW..WWWWW.W.WW
W.W.CW.C.W.W..WWWW..WWCW.WWW.C.WCCW
C.................................C
WWWWWW..W.WW.WWW.W.WWWWW.W.CCW.WWCW
CWWWCW.WWCWW.WWWWW.WCWWW.WWWWW.WCWC
.WCWWC.WWWWW.WCWCW.WWWCW.WWWCC..WCW
WWW.WW.CCCCW.CWCWC.WCWWW.WWWCW.WWWW
CWWWWW.WWWWC.WCCW..WWWWW.WWW.W.WWWC
C.................................C
WWWWWW.WCWWW.WWWWW.C..WW..WCWW..WW.
WWWWWW.WWWCW.WWWWW.WWCWW.WW.WW..WCC
WWCWW..WWWWW.CW......CWW.WWWW..WWWW
WWWWWW.WWWCW.CW.....WCWW.WWWWW.WWCW
WCWWCW.W.WWW.WW.....WWWW.W.W.W.WWWW
W.................................W
WCWCCW.CWWWC.CW.....WWWC.WCW.W.CW.W
WWWWW...WWWW.WWWWW.WW.WC.CCWWW.WWWW
WCWWWW..WC.C.WCW.W.CCWWW..WWWC.WCWW
CWCWWW.WWWWW.WWWWW.WWW.W.WCWC..CC.W
WWWW.C.CWCWW.WWCWC.WWCWC.WCWW..WWWC
W.................................W
WWC.CW.WWWCW.WCWWW.WCWWW.WWWWW.WCCW
C.W..W.WCWWW.CWCWW.WCWWW.WWWWW.WWWW
WWWWCW.CWWWW.WWWWW..WCWW.WWWWW.CWWW
CWWWWW.WWW.W.WWWWW.WW.WC..WWCW.CWWW
CWWWW..CWWWW.WWWWC.WWWWW.WWWWC..WWW
W.................................W
.WCCWW..WWW..WWCCW...CWW..W.WW.WCWW
WC.CWW.WWWWW.WWC.W.WWWWW.WCWCW.WCCW
WWWWWW.WWCWW.WWWWW.WWCWW..CWWW.WCWW
WCCWWCWWW.WWWCWWWWWWWWWWCCWWCWWW.WW`
};
