import { TourConfig } from "../TourConfig";

export const tour3: TourConfig = {
  id: 3,
  layout: `WW.WWWWWW.WWWWWWWW.WWWWWWWWWW..WW
W.WWWW....WW.WWWWW.WWWW..WWWW..WW
.WWW.W.WWWWW.WWWWW.WWWWW.WWWWW.WW
.WWWWW.WWWWW.WWWWW.WWWWW.WWWWW.WW
WWWWWW.WWWWW.WW.WW.WWWWW..WWWW.WW
WWWWWW.WWWWW.W.WWW.WWWWW.WWWWW.WW
W...............................W
.WW..W.WWWWW.WWWWW.W.WWW.WWWW..W.
.W.WWW.WWWW..WWWWW..WWWW.WWWWW.WW
WWWWWW.WWWWW.WWWWW.WWWWW.WWWWW..W
WWWWWW.WWWWW.WWWWW..WWWW.WWWWW.WW
WWW.WW.WW.WW.WWWWW.WWWWW.WWWWW.WW
W...............................W
W.WWWW.WWW.W.WWWWW.WWWWW.WWWWW.WW
WWWWWW.WWWWW.W.....WWWWW.WWWW..WW
WWWWWW.WWWWW.W.....WWWW..WWWWW..W
.WWWWW.WWWWW.W.....WWWWW.WWW.W.WW
.WWWWW.WW.WW.W.....WWWWW.WWWWW..W
W...............................W
WW.WWW.WWWWW.WWW.W.WWWW..W..WW.W.
WWWW.W.WWWWW.WWWWW.WWWWW.WWW.W..W
W..WWW..WWWW.WWWW..WWW.W.WWWWW.WW
WWWWWW..WWWW..WWWW.WW.WW.WWWWW..W
WWWWW..WWWWW.W.WWW.W.WWW.WWWWW.WW
W...............................W
WWWW.W.WWWW..WWWWW.WWWWW.WWWWW.WW
WWW.W..WWWWW.WWWWW.WWWWW.WWWWW.WW
WWWWWW.WWWWW.WWWWW.WW.WW.WW.WW.WW
WWWWWW.W..WW.W.WWW.WWWWW.WWWWW.WW
WWW.WW.WWWW..WW.WW.WWWWW.WWW.W.WW
................................W
WWWW.W.WWWWW.WWWWW.WWWW..WWWWW.WW
WWWWWWWWWWWWWWWWWWWW.WWWWWWWW.WWW`
};
