import { TourConfig } from "../TourConfig";

export const tour4: TourConfig = {
  id: 4,
  layout: `W.W.WWWWWWWWWW..WWWWWWWWWWWWWW.WWW
WWWWWW.W.WW..WWWWW.WWWWW.WW.WW.WWW
WW.WW..W..WW.WWW.W.WWWWW.WWWWW.WWW
W.WWWW.WWWWW.WWW.W.WW.WW.WWWW..WWW
WWWW.W.W.W.W.WWWWW.WWWWW.WW.WW.WWW
.WWWWW.WWWWW.WWWWW..WWWW.WWWWW.WWW
W................................W
WW.WWW.WWW.W.WWWWW.WWWWW.WWWW..WWW
WWWWWW.WWWWW.W.WWW.WW.WW.WW.WW.WWW
W.WWWW.W.WWW.WWWWW.WWWWW.WWW.W.WWW
.WWWWW.WWWWW.WWWWW.WWWWW.WWWWW.WWW
WWW..W.WWWWW.WW..W.WW.WW.WWWWW.WWW
W................................W
WWWWWW..WWW..WW.WW.W.WWW.WW.W..WWW
WWWWWW.WWWWW.WWWWW.WWWWW.WWWWW.WWW
WWWWWW.WW.WW.WW.....WWWW.WWWW..WWW
.WWWWW.WWWW...W.....WWWW.WWWWW.WWW
WWWWWW.WWWWW.WW.....WW.W.WWWWW.WWW
..................................
WWWWW..WWWW.........WWWW.WWWW..WWW
WWWWWW.W.WWW.WWWWW.WWWW..WWWWW.WWW
WWWWWW.WWWW..WWWWW.WWW.W.WWWWW..WW
WWWWWW.WWWWW.WWWWW.WWWWW.WWWWW.WWW
WWWWWW.WWWWW.WWW.W.WWWWW.WWWWW.WWW
W................................W
WWWWWW.WWWWW.WWWWW..WWWW.WWWW..WWW
WW.WWW.WW.WW.W.WWW.WWWWW.W..WW.WWW
WWW.WW.WW.WW.WWWWW.WWWWW.WWWWW.WWW
WWWWWW.WWWWW.WWWWW.WWWWW.WWWW..WWW
WWWWW..WWWWW.W.WWW.WWW.W.WWWWW.WWW
W................................W
W.WWW..WWWWW.WWWWW.WWWWW.WWWWW..WW
WWWWWW.WW.WW.WWWWW.WWWWW.WWWW..WWW
W.WWWWWWW.WWWWWWWWWWWWWWWWWWW.WW.W`
};
