import { TourConfig } from "../TourConfig";

export const tour9: TourConfig = {
  id: 9,
  layout: `W.WWWCW.CCCWW.CW##.WW..WW.WWWWWWWC.WCWW
WW.WWW.WWWWC.WW#W#.WWCWW.WWCW#.WWWCW.WW
WWCC#C.WWWW..WW....WCWWW.W.W#W.#W.W..#C
.WCCWW.WCW.C.WCWWW.WWWWW.WWWWW.#WCWW.CW
.WWWWW.#CWWW..WC.W.W.WW..WWW#..CWWWC.WC
WCWW.C.WW.WW.W#CWW.WW#WW.CWWWW.#WWWW.WW
C.....................................C
WCWWWW.WWWWW.W#WWW.CCWWC.WWWCW.WWWWW.WW
W#WWCW.WWWWW.WWWWC..#WWW..W.WW.WWCWW.W#
WWWW.W.CCWWW.WWWWW.CWWWC.WWWWC.WWWWW.WW
WCWWC#.CWWWW.WWWWW.WWWWW.WWCCW.W..W#.WW
WWCWWW.WW.WW.W.WWW.WC##W.WWWWW.W.WW#.CW
W.....................................W
WWWWWW.WWWW...CWWW.WWWWW.W.WWW.W.WWW..W
W...WW.WWWCW.WW.WC.WW.W#.WWCWW.W.WWW.WW
CCWCWW..WW.C.WW..W.WWCW..C.WWW.WWWCW.WW
CWCW#W.W.WWW..CCWC.WWW.#.WWWWW.WCWWW.CW
CWWCWC.WWCWC.WW.W.....C..#WWWW.WWWWW.WW
W.....................................C
CWWCWC.WWWWC.WWWC.....WC.CW#WW.W.WW#.WC
.WWW#W.WC.WW..WW......CW.WWWCC.W#WWW.WW
.WWWWW.WWWWW..WWW.....W#.WW#CW.W#WCC.WW
WW.WWW.WWWCW.WWW.C.WCWW..W#WWW.WWW#C.WC
WWW..C.W.WWW.C#WCW.WWWWC.WWWCC.WWWCC.W.
C.....................................C
W#WWW#..WWW..W#WWC.WWCWW.WWWWW..CW.W.WW
W.WWWW.WWW#W.CWW#W.WWW.W.WW.W..W.WCC.WW
WWWCCW.WCWC#.WWWW..WCW.W.W.CWW.WW.WW.WW
#WCWWW.WWWWW.CWWWW.CWWW..WWWWW.WWWWW.WC
#WCWWW.WCCWW.WWCWW.WWWWC.WWWWW.CCWCW.WW
W.....................................W
C.W#WW.WWWW#.WWW.W.WCCWC.WWCW..WWWCC.WW
C.WCWW.WWWWW.CW#WW.WWWW...WWWC..WWWW.CC
W.WWWW.WCWWW.WWC#W.WWWWC.WWWWW.WWCWC.WW
WWCWWW.WWW.C.WCW.W.CWWW..WWW#W.WCWWC.WW
WW.WWW.CCWCW.CWCWC.WWCW..CCW#W.WW#WC...
C.....................................C
.WC.W#.WWWWW.#WWWW.WCWCW.W.WCW.WWW#W.WW
CWWW.CCWCWWCWCCWWWWWWCW.CWCCW.WWWWWWCWW`
};
