import { TourConfig } from "../TourConfig";

export const tour12: TourConfig = {
  id: 12,
  layout: `WWCWWW.CWWCW.WWWCW.CWWWW.WWCWW.CWWWCW
CWWWWW.WWWWW.CWWWW.WWCWW.WWWWW.WWWWWC
WCWWWW.WCWWC.WWWWW.CWWWC.CWWCW.WWWWCW
WWWWCW.WWWWW.WWCWW.WWWWW.WWWWW.WCWWWW
WW.CWW.WWCWW.CWWWW.WWCWW.WWC.W.WWCWWW
WWWWWW.CWWWW.WWWWC.WWWWW.WWWWW.WWWWWC
C....................................C
CWWWWW.WWCWW.CWWWW.CWWCW.WWWWW.WWWWCW
WWWCWW.CWWWW.WWWWW.WWWWW.WWCWW.WCWWWW
WWWWWW.WWWCW.WWCWW.WWWCW.CWWWW.WWWWWW
WCCWWW.WWWWW.CWWWW.WWWWW.WWWWW.WWWCCW
WWWWWW.WWCWW.WWWWW.WWCWW.WWCWW.WWWWWW
C....................................C
WWWWCW.CWWWW.WWWWW.CWWWW.WWWCW.WWWWWW
WCWWWW.WWWWW.CWWCW.WWWWW.WWWWW.WWWWCW
WWWWWW.WWCWW.W...W.WWCWW.WWWWWW.WWWWW
WCWWWW.WWWWW.CWWCW.WWWWW.WWWWW.WWWWCW
WWWWCW.CWWWW.WWWWW.CWWWW.WWWCW.WWWWWW
C....................................C
WWWWWW.WWCWW.WWWWW.WWCWW.WWCWW.WWWWWW
WCCWWW.WWWWW.CWWWW.WWWWW.WWWWW.WWWCCW
WWWWWW.WWWCW.WWCWW.WWWCW.CWWWW.WWWWWW
WWWCWW.CWWWW.WWWWW.WWWWW.WWCWW.WCWWWW
CWWWWW.WWCWW.CWWWW.CWWCW.WWWWW.WWWWCW
C....................................C
WWWWWW.CWWWW.WWWWC.WWWWW.WWWWW.WWWWWC
WW.CWW.WWCWW.CWWWW.WWCWW.WWC.W.WWCWWW
WWWWCW.WWWWW.WWCWW.WWWWW.WWWWW.WCWWWW
WCWWWW.WCWWC.WWWWW.CWWWC.CWWCW.WWWWCW
CWWWWW.WWWWW.CWWWW.WWCWW.WWWWW.WWWWWC
.....................................
WWWCWC.CWWCW.WCWWW.CWWWW.CWWCW.CWWWCW`
};
