import { TourConfig } from "../TourConfig";

export const tour14: TourConfig = {
  id: 14,
  layout: `WWWWWCWWWWWWW.CWWWCWWWWW.WWWWWCWWWWWWWWW
CWWWWW.WWWWW.WWWWW.WWWWW.WWWWW.WWWWWC
WWWWWW.WWWWW.WWWWW.WWWWW.WWWWW.WWWWWW
WCWW.W.WWCWW.WW.WW.WWCWW.W.WWC.WWWWWW
WWWWWW.WWWWW.WWWWW.WWWWW.WWWWW.WWWWWW
CWWWWW.WWWWW.CWWWC.WWWWW.WWWWW.WWWWWC
C....................................C
WWWWWW.WW.WW.WWWWW.WW.WW.WWWWW.WWWWWW
CWWWWW.WWWWW.WWWWW.WWWWW.WWWWW.WWWWWC
WWWWWW.WWCWW.CWWWW.WWCWW.WWWWW.WWWWWW
WWWWWW.WWWWW.WWWWW.WWWWW.WWWWW.WWWWWW
CWWWWW.WW.WW.WWWWW.WW.WW.WWWWW.WWWWWC
W....................................W
WWWWWW.WWWWW.WWWWW.WWWWW.WWWWW.WWWWWW
WWCWWW.WWWWW.WWCWW.WWWWW.WWWWW.WWWCWW
WWWWWW.WWWWW.W...W.WWWWW.WWWWW.WWWWWW
WWCWWW.WWWWW.WWCWW.WWWWW.WWWWW.WWWCWW
WWWWWW.WWWWW.WWWWW.WWWWW.WWWWW.WWWWWW
W....................................W
CWWWWW.WW.WW.WWWWW.WW.WW.WWWWW.WWWWWC
WWWWWW.WWWWW.WWWWW.WWWWW.WWWWW.WWWWWW
WWWWWW.WWCWW.CWWWW.WWCWW.WWWWW.WWWWWW
CWWWWW.WWWWW.WWWWW.WWWWW.WWWWW.WWWWWC
WWWWWW.WW.WW.WWWWW.WW.WW.WWWWW.WWWWWW
C....................................C
CWWWWW.WWWWW.CWWWC.WWWWW.WWWWW.WWWWWC
WWWWWW.WWWWW.WWWWW.WWWWW.WWWWW.WWWWWW
WCWW.W.WWCWW.WW.WW.WWCWW.W.WWC.WWWWWW
WWWWWW.WWWWW.WWWWW.WWWWW.WWWWW.WWWWWW
CWWWWW.WWWWW.WWWWW.WWWWW.WWWWW.WWWWWC
.....................................
CWWWWCWWWWWWW.CWWWCWWWWW.CWWWWCWWWWWWWW`
};
